Fix: update storefront
felleslosninger/tlp-organization-chart pull request #64
Opened 2024-03-22 11:40 UTC by jensmo98

Updated the storefront with new and correct data. 

Implemented native select component from DS, to switch between different chart

2024-03-22 11:58 UTC, Barsnes requested changes

2024-03-22 11:58 UTC, Barsnes commented on apps/storefront/app/components/Chart/Chart.client.tsx
> +    </>
I think we should make an object outside of the component, preferably in it's own file - so we can easier add and remove sets. Right now it's fine since we have two, but in the future we may want to add more, or remove some.

When we have an object we can loop over it on line 35, and then look up directly in `handleChange`

2024-03-25 13:08 UTC, Barsnes commented
Can we also remove the `z-index` on `.wrapper`? We currently can't click on the link

2024-03-26 07:51 UTC, jensmo98 commented on apps/storefront/app/components/Chart/Chart.client.tsx
> +  console.log(charts);
haha, ait

2024-03-26 07:53 UTC, Barsnes approved these changes

2024-03-26 07:53 UTC, merged